Update to ruby 2.7.2
lifull-dev/bucky-management pull request #29
Opened 2021-03-17 06:38 UTC by naotospace

2021-03-21 10:40 UTC, rueyaa332266 commented on Gemfile
> +  gem 'rubocop', require: false
Maybe rubocop-rails is also needed?

2021-03-21 10:40 UTC, rueyaa332266 requested changes
Please check the comment.

2021-03-22 00:31 UTC, naotospace commented on Gemfile
> +  gem 'rubocop', require: false
Thanks! Fixed.

2021-03-23 00:00 UTC, rueyaa332266 approved these changes
LGTM

2021-03-23 00:00 UTC, merged