Maint/test reports v2
lifull-dev/bucky-management pull request #45
Opened 2022-11-10 08:51 UTC by T-Y89

I created job_tree in /test_report

2022-11-14 04:59 UTC, nk-ty requested changes
@T-Y89 
Thanks for your suggestion.
I checked, could you please check my comments?

2022-11-14 04:59 UTC, nk-ty commented on app/controllers/test_reports_controller.rb
> +    all_roots = Job.all.where("command_and_option not like '%rerun%'").order('jobs.id DESC')
It might be a good idea to  move to job model as this line depends on job tables in in database.

2022-11-14 04:59 UTC, nk-ty commented on app/controllers/test_reports_controller.rb
> +    children_jobs = Job.join_with_suites(Job.select('id').where("command_and_option like '%rerun%'").page(params[:page]).per(per_page * 3).order('jobs.id DESC').to_a)
(Same) It might be a good idea to move to job model as this line depends on job tables in in database.

2022-11-14 04:59 UTC, nk-ty commented on app/controllers/test_reports_controller.rb
> +  def create_job_tree(parent_jobs, children_jobs)
(Same) It might be a good idea to move to job model as this line depends on job tables in in database.

2022-11-14 07:24 UTC, T-Y89 commented
I fixed codes for your advices.

I couldn't  fix [this](https://github.com/lifull-dev/bucky-management/blob/d78229927775d338461f7c310331e4e7f8b96693/app/controllers/test_reports_controller.rb#L8), and [this](https://github.com/lifull-dev/bucky-management/blob/d78229927775d338461f7c310331e4e7f8b96693/app/controllers/test_reports_controller.rb#L10) because I couldn't locate the data of [:page]

2022-11-14 08:50 UTC, nk-ty approved these changes

2022-11-18 08:53 UTC, nk-ty requested changes
@T-Y89 
I checked other than `docker-compose.with_mysql.yml` first.

2022-11-18 08:53 UTC, nk-ty commented on app/views/test_reports/index.html.slim
> +        - indent = "&nbsp;""&nbsp;" * job[:indent_num]
```suggestion
        - indent = job[:indent_num] == 0 ? "" : "&nbsp;&nbsp;" * job[:indent_num] + "└&nbsp;"
```
↓
```
1
  └ 2
  └ 3
    └ 4

2022-11-18 08:53 UTC, nk-ty commented on app/controllers/test_reports_controller.rb
> +    # 1ページで取得する小ジョブ数はper_page * 4件分で最低限取れると判断
Could you please translate to English?

2022-11-18 08:53 UTC, nk-ty commented on app/models/job.rb
> +      # 特定のID "より大きい" データを取得するため +1 する
Could you please translate to English?

2022-11-22 03:55 UTC, nk-ty reviewed
Thanks for your fix.

Add new comment.

2022-11-22 03:55 UTC, nk-ty commented on app/controllers/test_reports_controller.rb
> +    # I guessed the number of chiled_jobs per page is obtained by per_page*4
It might be a good idea to delete subject.
```suggestion
    # Guessed the number of chiled_jobs per page is obtained by per_page*4
```

2022-11-22 03:55 UTC, nk-ty commented on app/models/job.rb
> +      # To get id which is more than specific id, I wrote +1
It might be a good idea to delete subject.
```suggestion
      # `+ 1` is for getting id which is more than specific id
```

2022-11-22 08:55 UTC, nk-ty approved these changes
LGTM!

2022-12-02 09:23 UTC, nk-ty approved these changes

2022-12-02 09:23 UTC, merged