showページから直接issueを作成できるようにした
lifull-dev/bucky-management pull request #52
Opened 2023-07-07 10:42 UTC by T-Y89

2023-07-07 11:03 UTC, T-Y89 commented
動作ログです
https://drive.google.com/file/d/10GyymPg05T89bru8AKV4XYfoWQlmJovq/view?usp=sharing
https://drive.google.com/file/d/1CeIVDnkijwxSZZ9adFochTbam71syiKr/view?usp=sharing

2023-07-11 00:41 UTC, nk-ty requested changes
@T-Y89 
Added suggestions.

2023-07-11 00:41 UTC, nk-ty commented on app/helpers/test_report_helper.rb
> +    full_path.sub(%r{(https://github\.com/lifull/ldat-homes).*}, '\1')
```suggestion
    matched = full_path.match(/^https:\/\/github.com\/([^\/]+)\/([^\/]+)\/.*$/)
    return [nil, nil] if matched.nil?
    matched.captures
```

2023-07-11 00:41 UTC, nk-ty commented on app/helpers/test_report_helper.rb
> +  def delete_owner_and_ripository(full_path)
```suggestion
  def owner_and_ripository(full_path)
```

2023-07-11 00:41 UTC, nk-ty commented on app/views/test_reports/_detail_table.html.slim
> +            = link_to ftc.case_name, base_url + file_path, target: '_blank'
```suggestion
            = link_to ftc.case_name, base_url + file_path + "#:~:text=" + ftc.case_name, target: '_blank'
```

2023-07-11 10:54 UTC, nk-ty requested changes
Thanks!
Could you please new suggestions?

2023-07-11 10:54 UTC, nk-ty commented on app/helpers/test_report_helper.rb
> +  def owner_and_ripository(full_path)
```suggestion
  def github_repo_base_url(full_path)
```

2023-07-11 10:54 UTC, nk-ty commented on app/views/test_reports/_detail_table.html.slim
> +            = link_to 'create_issue', owner_and_ripository(base_url) + issue_path, target: '_blank'
```suggestion
            = link_to 'create_issue', github_repo_base_url(base_url) + issue_path, target: '_blank'
```

2023-07-11 10:54 UTC, nk-ty commented on spec/helpers/test_report_helper_spec.rb
> +# require 'app/helpers/test_report_helper.rb'
```suggestion
```

2023-07-12 00:40 UTC, T-Y89 commented
logs 

```ruby
bundle exec rspec spec/helpers/test_report_helper_spec.rb
.

Finished in 0.89538 seconds (files took 25.18 seconds to load)
1 example, 0 failures
```

2023-07-12 03:59 UTC, nk-ty approved these changes

2023-07-12 04:02 UTC, merged